language: node_js

node_js:
  - "11"
  - "10"
  - "8"

install:
  - npm install -g codecov

script:
  - npm run lint
  - npm run unit
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always

