language: node_js

node_js:
  - "11"
  - "10"
  - "8"

install:
  - npm install -g codecov && npm install

script:
  - npm run lint
  - npm run coverage
  - npm run report-coverage

notifications:
  email:
    on_success: never
    on_failure: always

